# Generated by Django 2.2.13 on 2020-09-19 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appl', '0064_auto_20200409_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('admission_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionProject')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('primary_order', models.IntegerField()),
                ('secondary_order', models.IntegerField(default=0)),
                ('criteria_type', models.CharField(max_length=30)),
                ('score_type', models.CharField(max_length=30)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unit', models.CharField(default='', max_length=30)),
                ('desscription', models.TextField(default='')),
                ('admission_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.Major')),
            ],
        ),
        migrations.CreateModel(
            name='MajorCuptCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.CharField(max_length=30, unique=True)),
                ('program_type', models.CharField(max_length=5)),
                ('major_code', models.CharField(max_length=5)),
                ('title', models.TextField()),
                ('major_title', models.TextField(blank=True, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.Faculty')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.Major')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumMajorAdmissionCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.IntegerField()),
                ('admission_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criteria.AdmissionCriteria')),
                ('curriculum_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criteria.CurriculumMajor')),
            ],
        ),
        migrations.AddField(
            model_name='curriculummajor',
            name='admission_criterias',
            field=models.ManyToManyField(through='criteria.CurriculumMajorAdmissionCriteria', to='criteria.AdmissionCriteria'),
        ),
        migrations.AddField(
            model_name='curriculummajor',
            name='admission_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionProject'),
        ),
        migrations.AddField(
            model_name='curriculummajor',
            name='cupt_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criteria.MajorCuptCode'),
        ),
        migrations.AddField(
            model_name='curriculummajor',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.Major'),
        ),
    ]
