# Generated by Django 2.2.13 on 2020-09-20 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculummajor',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appl.Major'),
        ),
        migrations.AlterField(
            model_name='majorcuptcode',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appl.Major'),
        ),
        migrations.AlterField(
            model_name='majorcuptcode',
            name='program_code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='majorcuptcode',
            name='program_type',
            field=models.CharField(max_length=30),
        ),
    ]
