# Generated by Django 2.2.13 on 2020-09-21 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0064_auto_20200409_0420'),
        ('criteria', '0002_auto_20200920_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculummajor',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appl.Faculty'),
            preserve_default=False,
        ),
    ]
