# Generated by Django 2.2.13 on 2020-09-21 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0003_curriculummajor_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scorecriteria',
            old_name='desscription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='scorecriteria',
            name='admission_criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criteria.AdmissionCriteria'),
        ),
    ]
