# Generated by Django 2.2.13 on 2020-09-21 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0064_auto_20200409_0420'),
        ('criteria', '0004_auto_20200921_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncriteria',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appl.Faculty'),
        ),
        migrations.AddField(
            model_name='curriculummajoradmissioncriteria',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
