# Generated by Django 2.2.13 on 2020-09-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0005_auto_20200921_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorcuptcode',
            name='program_type_code',
            field=models.CharField(default='A', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='majorcuptcode',
            name='major_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddConstraint(
            model_name='majorcuptcode',
            constraint=models.UniqueConstraint(fields=('program_code', 'major_code'), name='unique_program_major'),
        ),
    ]
