# Generated by Django 2.2.13 on 2020-09-24 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0005_auto_20200921_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecriteria',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='criteria.ScoreCriteria'),
        ),
        migrations.AddField(
            model_name='scorecriteria',
            name='relation',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
