# Generated by Django 2.2.13 on 2020-09-24 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0006_auto_20200924_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='majorcuptcode',
            options={'ordering': ['program_type_code', 'program_code']},
        ),
    ]
