# Generated by Django 2.2.13 on 2020-09-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0006_auto_20200924_1637'),
        ('criteria', '0007_auto_20200924_1639'),
    ]

    operations = [
    ]
