# Generated by Django 2.2.13 on 2020-10-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0008_merge_20200924_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncriteria',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
