# Generated by Django 2.2.13 on 2020-10-07 03:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0009_admissioncriteria_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncriteria',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
