# Generated by Django 2.2.13 on 2020-10-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0011_auto_20201010_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorcuptcode',
            name='component_weight_type',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
