# Generated by Django 2.2.13 on 2020-10-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0013_auto_20201016_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncriteria',
            name='created_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='admissioncriteria',
            name='curriculum_majors_json',
            field=models.TextField(blank=True),
        ),
    ]
