# Generated by Django 2.2.13 on 2020-10-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0014_auto_20201020_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncriteria',
            name='additional_condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='admissioncriteria',
            name='additional_description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
