# Generated by Django 2.2.13 on 2020-10-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0015_auto_20201029_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissioncriteria',
            name='additional_condition',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
