# Generated by Django 3.2.7 on 2021-10-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0017_admissioncriteria_additional_interview_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissioncriteria',
            name='additional_interview_condition',
            field=models.TextField(blank=True),
        ),
    ]
