# Generated by Django 3.2.15 on 2022-09-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0019_auto_20220828_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissioncriteria',
            name='accepted_student_curriculum_type_flags',
            field=models.CharField(blank=True, default='*', max_length=10),
        ),
    ]
