# Generated by Django 4.1.1 on 2023-09-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0022_importedcriteriajson'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncriteria',
            name='accepted_graduate_year_flags',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
