# Generated by Django 4.1.1 on 2023-10-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0023_admissioncriteria_accepted_graduate_year_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuptExportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_filename', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='admissioncriteria',
            name='accepted_graduate_year_flags',
            field=models.CharField(blank=True, default='*', max_length=10),
        ),
    ]
