# Generated by Django 4.1.13 on 2024-04-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0024_cuptexportlog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuptexportlog',
            options={'ordering': ['-created_at']},
        ),
    ]
