# Generated by Django 4.1.13 on 2024-08-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0025_alter_cuptexportlog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncriteria',
            name='interview_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันสัมภาษณ์'),
        ),
    ]
