# Generated by Django 4.1.13 on 2024-08-30 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0085_admissionproject_display_rank'),
        ('criteria', '0026_admissioncriteria_interview_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionProjectFacultyInterviewDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_major_specific', models.BooleanField(default=True, verbose_name='ระบุแยกตามสาขา')),
                ('interview_date', models.DateField(blank=True, null=True, verbose_name='วันสัมภาษณ์')),
                ('admission_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.admissionproject')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.faculty')),
            ],
            options={
                'unique_together': {('admission_project', 'faculty')},
            },
        ),
    ]
