# Generated by Django 4.1.13 on 2024-10-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0027_admissionprojectfacultyinterviewdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncriteria',
            name='custom_interview_date_str',
            field=models.TextField(blank=True),
        ),
    ]
