# Generated by Django 4.1.13 on 2024-10-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0029_cuptexportcustomproject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuptexportadditionalprojectrule',
            options={'ordering': ['program_major_code', 'custom_project']},
        ),
        migrations.AlterModelOptions(
            name='cuptexportcustomproject',
            options={'ordering': ['cupt_code']},
        ),
        migrations.AlterField(
            model_name='cuptexportcustomproject',
            name='cupt_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
