# Generated by Django 4.1.13 on 2024-10-11 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0031_cuptexportadditionalprojectrule_admission_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuptexportadditionalprojectrule',
            options={'ordering': ['program_major_codes', 'custom_project']},
        ),
        migrations.RenameField(
            model_name='cuptexportadditionalprojectrule',
            old_name='program_major_code',
            new_name='program_major_codes',
        ),
    ]
