# Generated by Django 4.1.13 on 2024-10-11 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0032_alter_cuptexportadditionalprojectrule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuptexportadditionalprojectrule',
            name='program_major_codes',
            field=models.CharField(max_length=100),
        ),
    ]
