# Generated by Django 4.1.13 on 2025-08-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0034_alter_cuptexportadditionalprojectrule_program_major_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncriteria',
            name='additional_admission_form_fields_json',
            field=models.TextField(blank=True),
        ),
    ]
