# Generated by Django 4.1.13 on 2025-08-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0035_admissioncriteria_additional_admission_form_fields_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncriteria',
            name='is_from_last_year',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissioncriteria',
            name='last_year_major_titles',
            field=models.TextField(blank=True),
        ),
    ]
