# Generated by Django 4.1.13 on 2025-09-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0036_admissioncriteria_is_from_last_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncriteria',
            name='additional_notice',
            field=models.TextField(blank=True),
        ),
    ]
