# Generated by Django 5.2.16 on 2026-07-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0037_admissioncriteria_additional_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissioncriteria',
            name='additional_admission_upload_fields_json',
            field=models.TextField(blank=True),
        ),
    ]
