# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appl', '0017_auto_20171002_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appl.School')),
            ],
        ),
    ]
