# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0019_auto_20171005_1617'),
        ('regis', '0003_auto_20171006_1337'),
        ('supplements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSupplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('json_data', models.TextField(blank=True)),
                ('admission_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionProject')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regis.Applicant')),
            ],
        ),
    ]
