# Generated by Django 2.2.5 on 2019-12-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplements', '0003_advancedplacementapplicant_advancedplacementresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedplacementapplicant',
            name='student_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
