version: '3'

services:

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: example

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_ARBITARY: 1
      PMA_USER: root
      PMA_PASSWORD: example
      UPLOAD_LIMIT: 64M
