# Generated by Django 2.1.3 on 2018-11-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrconfirmations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrconfirmation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Success'), (500, 'Error')], default=0),
        ),
    ]
