# Generated by Django 2.1.3 on 2018-12-10 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0060_projectuploadeddocument_document_key'),
        ('qrconfirmations', '0002_qrconfirmation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrconfirmation',
            name='payment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appl.Payment'),
        ),
    ]
