# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='admission_projects',
            field=models.ManyToManyField(blank=True, to='appl.AdmissionProject'),
        ),
    ]
