# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_checkmarkgroup_judgecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='judgecomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='profile',
            name='major_number',
            field=models.IntegerField(default=0, verbose_name='หมายเลขสาขา (กรณีที่ดูแลโครงการเดียว)'),
        ),
    ]
