# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-01 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_auto_20171101_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgecomment',
            name='author_username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
