# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_judgecomment_author_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgecomment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
