# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_judgecomment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgecomment',
            name='is_super',
            field=models.BooleanField(default=False),
        ),
    ]
