# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0039_auto_20171116_1451'),
        ('backoffice', '0006_judgecomment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgecomment',
            name='admission_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionProject'),
        ),
        migrations.AddField(
            model_name='judgecomment',
            name='admission_round',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionRound'),
        ),
        migrations.AddField(
            model_name='judgecomment',
            name='is_shared_in_major',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='judgecomment',
            name='major',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appl.Major'),
        ),
    ]
