# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-14 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0008_auto_20180413_0232'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='majorinterviewcalldecision',
            index=models.Index(fields=['admission_round', 'admission_project'], name='backoffice__admissi_f2ae4c_idx'),
        ),
    ]
