# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0008_judgecomment_major'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judgecomment',
            old_name='major',
            new_name='major_number',
        ),
    ]
