# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-23 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0055_auto_20180523_0259'),
        ('regis', '0008_auto_20180131_1151'),
        ('backoffice', '0009_auto_20180414_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantMajorResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionProject')),
                ('admission_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionResult')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regis.Applicant')),
                ('exam_score', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appl.ExamScore')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.Major')),
            ],
        ),
        migrations.AddIndex(
            model_name='applicantmajorresult',
            index=models.Index(fields=['major', 'admission_project'], name='backoffice__major_i_0bb961_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantmajorresult',
            index=models.Index(fields=['applicant'], name='backoffice__applica_95042d_idx'),
        ),
    ]
