# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0009_auto_20171113_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgecomment',
            name='admission_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='judgecomment',
            name='project',
            field=models.IntegerField(default=0),
        ),
    ]
