# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-23 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0055_auto_20180523_0259'),
        ('regis', '0008_auto_20180131_1151'),
        ('backoffice', '0010_auto_20180523_1006'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicantmajorresult',
            unique_together=set([('major', 'admission_project', 'applicant')]),
        ),
        migrations.AddIndex(
            model_name='applicantmajorresult',
            index=models.Index(fields=['major', 'admission_project', 'applicant'], name='backoffice__major_i_3bec96_idx'),
        ),
    ]
