# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0010_auto_20171114_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judgecomment',
            old_name='admission_round',
            new_name='admission_round_id',
        ),
        migrations.RenameField(
            model_name='judgecomment',
            old_name='project',
            new_name='project_id',
        ),
    ]
