# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0036_auto_20171107_0338'),
        ('backoffice', '0011_auto_20171114_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgecomment',
            name='admission_round_id',
        ),
        migrations.RemoveField(
            model_name='judgecomment',
            name='project_id',
        ),
        migrations.AddField(
            model_name='judgecomment',
            name='admission_round',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionRound'),
        ),
        migrations.AddField(
            model_name='judgecomment',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionProject'),
        ),
    ]
