# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-24 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0014_auto_20180523_1301'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='applicantmajorresult',
            index=models.Index(fields=['admission_project', 'applicant'], name='backoffice__admissi_b1c449_idx'),
        ),
    ]
