# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-24 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0016_applicantmajorresult_other_major_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantmajorresult',
            name='other_major_scores',
            field=models.CharField(blank='', default='', max_length=50),
        ),
    ]
