# Generated by Django 2.1.3 on 2018-11-19 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0017_applicantmajorresult_other_major_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantmajorresult',
            name='admission_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appl.AdmissionResult'),
        ),
        migrations.AlterField(
            model_name='applicantmajorresult',
            name='project_application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appl.ProjectApplication'),
        ),
        migrations.AlterField(
            model_name='judgecomment',
            name='admission_project',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appl.AdmissionProject'),
        ),
        migrations.AlterField(
            model_name='judgecomment',
            name='admission_round',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appl.AdmissionRound'),
        ),
        migrations.AlterField(
            model_name='judgecomment',
            name='major',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appl.Major'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='faculty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appl.Faculty', verbose_name='คณะที่สังกัด'),
        ),
    ]
