# Generated by Django 2.1.3 on 2019-01-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0018_auto_20181119_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_number_adjustment_admin',
            field=models.BooleanField(default=False, verbose_name='สำหรับปรับจำนวน'),
        ),
    ]
