# Generated by Django 2.1.3 on 2019-01-31 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0061_major_cupt_full_code'),
        ('backoffice', '0019_profile_is_number_adjustment_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_code', models.CharField(max_length=10, unique=True)),
                ('major_code', models.CharField(max_length=5)),
                ('study_type_code', models.CharField(max_length=3)),
                ('title', models.CharField(max_length=200)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.Faculty')),
            ],
        ),
    ]
