# Generated by Django 2.1.3 on 2019-01-31 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0061_major_cupt_full_code'),
        ('backoffice', '0020_adjustmentmajor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentMajorSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_round_number', models.IntegerField()),
                ('major_full_code', models.CharField(max_length=10)),
                ('admission_project_title', models.CharField(max_length=100)),
                ('original_slots', models.IntegerField()),
                ('current_slots', models.IntegerField()),
                ('adjustment_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.AdjustmentMajor')),
                ('admission_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionRound')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.Faculty')),
            ],
        ),
    ]
