# Generated by Django 2.1.3 on 2019-02-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0022_auto_20190204_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjustmentmajorslot',
            options={'ordering': ['admission_round_number', 'cupt_code']},
        ),
        migrations.AddField(
            model_name='adjustmentmajorslot',
            name='confirmed_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adjustmentmajorslot',
            name='is_confirmed_by_faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adjustmentmajorslot',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adjustmentmajorslot',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
