# Generated by Django 2.2.13 on 2020-10-04 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0064_auto_20200409_0420'),
        ('backoffice', '0023_auto_20190204_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='campus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appl.Campus', verbose_name='วิทยาเขต'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_campus_admin',
            field=models.BooleanField(default=False, verbose_name='ดูแลข้อมูลในวิทยาเขต'),
        ),
    ]
