# Generated by Django 2.2.17 on 2021-02-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0024_auto_20201004_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustmentmajor',
            name='full_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
