# Generated by Django 2.2.17 on 2021-02-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0025_auto_20210224_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustmentmajor',
            name='major_code',
            field=models.CharField(max_length=20),
        ),
    ]
