# Generated by Django 2.2.17 on 2021-02-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0026_auto_20210224_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustmentmajorslot',
            name='major_full_code',
            field=models.CharField(max_length=20),
        ),
    ]
