# Generated by Django 2.2.17 on 2021-02-24 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0027_auto_20210224_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adjustment_major_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
