# Generated by Django 2.2.17 on 2021-05-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0028_profile_adjustment_major_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjustmentmajorslot',
            name='admission_project_title',
            field=models.CharField(max_length=200),
        ),
    ]
