# Generated by Django 4.1.7 on 2023-03-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0030_interviewdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdescription',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันและเวลาการสัมภาษณ์'),
        ),
        migrations.AddField(
            model_name='interviewdescription',
            name='is_additional_documents_required',
            field=models.BooleanField(default=False, verbose_name='การส่งเอกสารเพิ่มเติม'),
        ),
    ]
