# Generated by Django 4.1.7 on 2023-03-26 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criteria', '0022_importedcriteriajson'),
        ('appl', '0080_alter_educationalprofile_sci_credit'),
        ('backoffice', '0031_interviewdescription_interview_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewdescription',
            name='major',
        ),
        migrations.CreateModel(
            name='AddmissionProjectMajorCuptCodeInterviewDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.admissionround')),
                ('interview_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_prject_major_cupt_code', to='backoffice.interviewdescription')),
                ('major_cupt_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criteria.majorcuptcode')),
            ],
        ),
    ]
