# Generated by Django 4.1.7 on 2023-03-28 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0080_alter_educationalprofile_sci_credit'),
        ('criteria', '0022_importedcriteriajson'),
        ('backoffice', '0034_rename_addmissionprojectmajorcuptcodeinterviewdescription_admissionprojectmajorcuptcodeinterviewdesc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionprojectmajorcuptcodeinterviewdescription',
            name='admission_project',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='appl.admissionproject'),
        ),
        migrations.AlterField(
            model_name='admissionprojectmajorcuptcodeinterviewdescription',
            name='major_cupt_code',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='criteria.majorcuptcode'),
        ),
    ]
