# Generated by Django 4.1.7 on 2023-03-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0035_alter_admissionprojectmajorcuptcodeinterviewdescription_admission_project_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='admissionprojectmajorcuptcodeinterviewdescription',
            constraint=models.UniqueConstraint(fields=('admission_project', 'major_cupt_code'), name='unique_admission_project_major_cupt_code'),
        ),
    ]
