# Generated by Django 4.1.7 on 2023-03-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0036_admissionprojectmajorcuptcodeinterviewdescription_unique_admission_project_major_cupt_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewdescription',
            name='contacts',
            field=models.JSONField(blank=True, default=list, verbose_name='ข้อมูลการติดต่อ'),
        ),
    ]
