# Generated by Django 4.1.7 on 2023-03-29 23:51

import backoffice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0037_alter_interviewdescription_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewdescription',
            name='description_image',
            field=models.FileField(blank=True, upload_to=backoffice.models.interview_description_image_path, verbose_name='รูปประกอบการเตรียมตัว'),
        ),
        migrations.AlterField(
            model_name='interviewdescription',
            name='preparation_image',
            field=models.FileField(blank=True, upload_to=backoffice.models.interview_preparation_image_path, verbose_name='รูปประกอบการเตรียมตัว'),
        ),
    ]
