# Generated by Django 4.1.7 on 2023-04-01 23:31

import backoffice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0038_alter_interviewdescription_description_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdescription',
            name='video_conference_platform',
            field=models.TextField(blank=True, verbose_name='ช่องทางการสัมภาษณ์ออนไลน์'),
        ),
        migrations.AlterField(
            model_name='interviewdescription',
            name='description_image',
            field=models.FileField(blank=True, upload_to=backoffice.models.interview_description_image_path, verbose_name='รูปประกอบการสัมภาษณ์'),
        ),
        migrations.AlterField(
            model_name='interviewdescription',
            name='is_additional_documents_required',
            field=models.BooleanField(choices=[(False, 'ไม่มี'), (True, 'ต้องส่งเอกสารหรือส่งลิงก์เพิ่มเติม (กรุณาแจ้งรายละเอียดในส่วนการสัมภาษณ์ด้วย)')], default=False, verbose_name='การส่งเอกสารเพิ่มเติม'),
        ),
    ]
