# Generated by Django 4.1.1 on 2023-04-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0039_interviewdescription_video_conference_platform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewdescription',
            name='is_additional_documents_required',
        ),
        migrations.AddField(
            model_name='interviewdescription',
            name='additional_documents_option',
            field=models.IntegerField(choices=[(0, 'ไม่มี'), (1, 'ต้องส่งเอกสารหรือส่งลิงก์เพิ่มเติม (อัพโหลดในระบบ)'), (2, 'ต้องส่งเอกสารหรือส่งลิงก์เพิ่มเติม (ส่งทางอื่น กรุณาแจ้งในรายละเอียดการเตรียมตัว)')], default=0, verbose_name='การส่งเอกสารเพิ่มเติม'),
        ),
    ]
