# Generated by Django 4.1.1 on 2023-04-10 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0080_alter_educationalprofile_sci_credit'),
        ('backoffice', '0040_remove_interviewdescription_is_additional_documents_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdescription',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appl.major'),
        ),
    ]
