# Generated by Django 4.1.1 on 2023-04-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0041_interviewdescription_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdescription',
            name='span_option',
            field=models.IntegerField(choices=[(0, 'เชื่อมโยงแยกโครงการ-สาขา'), (1, 'เชื่อมโยงทุกสาขาในโครงการนี้'), (2, 'เชื่อมโยงทุกโครงการของสาขานี้')], default=0, verbose_name='การเชื่อมโยงรายละเอียดการสัมภาษณ์'),
        ),
        migrations.AlterField(
            model_name='interviewdescription',
            name='additional_documents_option',
            field=models.IntegerField(choices=[(0, 'ไม่มี'), (1, 'ต้องส่งเอกสารหรือส่งลิงก์เพิ่มเติม (อัพโหลดในระบบ, กรุณาแจ้งรายละเอียดในการเตรียมตัว)'), (2, 'ต้องส่งเอกสารหรือส่งลิงก์เพิ่มเติม (ส่งช่องทางอื่น, กรุณาแจ้งในรายละเอียดในการเตรียมตัว)')], default=0, verbose_name='การส่งเอกสารเพิ่มเติม'),
        ),
    ]
