# Generated by Django 4.1.1 on 2023-04-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0043_alter_interviewdescription_span_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewdescription',
            name='span_option',
            field=models.IntegerField(choices=[(0, 'ไม่มีการเชื่อมโยงไปยังสาขาหรือโครงการอื่น'), (1, 'เชื่อมโยงทุกสาขาในโครงการนี้'), (2, 'เชื่อมโยงทุกโครงการของสาขานี้'), (3, 'เชื่อมโยงโดยระบุโครงการ-สาขา')], default=0, verbose_name='การเชื่อมโยงรายละเอียดการสัมภาษณ์'),
        ),
        migrations.AlterField(
            model_name='interviewdescription',
            name='video_conference_platform',
            field=models.TextField(blank=True, choices=[('webex', 'Cisco Webex'), ('zoom', 'Zoom'), ('google-meet', 'Google Meet'), ('other', 'โปรแกรมอื่น (กรุณาระบุในรายละเอียด)'), ('', 'ไม่ระบุ')], verbose_name='ช่องทางการสัมภาษณ์ออนไลน์'),
        ),
    ]
