# Generated by Django 4.1.13 on 2025-03-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0047_adjustmentmajorslot_confirmed_canceled_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkmarkgroup',
            name='is_multimajor_criteria_passed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='checkmarkgroup',
            name='updated_multimajor_criteria_passed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
