# Generated by Django 4.1.13 on 2025-04-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0048_checkmarkgroup_is_multimajor_criteria_passed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_criteria_check_permission',
            field=models.BooleanField(default=False, verbose_name='สามารถตรวจสอบเกณฑ์พื้นฐานได้พิเศษ'),
        ),
    ]
