# Generated by Django 4.1.13 on 2025-10-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0049_profile_has_criteria_check_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmenuconfig',
            name='menu_flag_json',
            field=models.TextField(help_text='Available options are td-interview-result,score-viewable-interview-call-by-scores,score-viewable-dropdown-show-applicant,not-score-viewable-show-applicant,interview-form-edit,td-show-scores,td-applicant-info,td-applicant-info-dropdown-show-applicant,td-applicant-info-dropdown-show-scores,download-dropdown,download-gen-info,download-scores,download-scores-tgat-tpat-label,download-scores-only-interview,download-gen-info-interview,download-interview-form,project_index_message,applicant_score_list_message'),
        ),
    ]
