# Generated by Django 4.1.13 on 2026-01-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0051_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmentmajorslot',
            name='num_accepted_applications',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='adjustmentmajorslot',
            name='num_applications',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
