# Generated by Django 4.1.13 on 2026-01-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0052_adjustmentmajorslot_num_accepted_applications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorSlotStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('full_code', models.CharField(max_length=20)),
                ('json_data', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('year', 'full_code')},
            },
        ),
    ]
