# Generated by Django 4.1.13 on 2026-02-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0053_majorslotstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewdescription',
            name='is_multiday_interview',
            field=models.BooleanField(default=False, verbose_name='สัมภาษณ์หลายวัน'),
        ),
    ]
