# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 12:44
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('short_title', models.CharField(max_length=200)),
                ('general_conditions', models.TextField(blank=True)),
                ('column_descriptions', models.TextField(blank=True)),
                ('descriptions', models.TextField(blank=True, verbose_name='รายละเอียดโครงการ')),
                ('short_descriptions', models.CharField(blank=True, max_length=400, verbose_name='รายละเอียดโครงการ (สั้น) แสดงในหน้าแรก')),
                ('slots', models.IntegerField(default=0, verbose_name='จำนวนรับ')),
                ('major_detail_visible', models.BooleanField(default=False, verbose_name='แสดงรายละเอียดสาขา')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionProjectRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_dates', models.CharField(max_length=100)),
                ('admission_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionProject')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('subround_number', models.IntegerField(default=0)),
                ('rank', models.IntegerField()),
                ('short_descriptions', models.CharField(blank=True, max_length=400, verbose_name='รายละเอียดสั้น ๆ (แสดงในหน้าแรก)')),
                ('admission_dates', models.CharField(blank=True, max_length=200, verbose_name='กำหนดการ')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'campuses',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.Campus')),
            ],
            options={
                'verbose_name_plural': 'faculties',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('slots', models.IntegerField()),
                ('slots_comments', models.TextField(blank=True)),
                ('detail_items_csv', models.TextField()),
                ('admission_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionProject')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.Faculty')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='admissionprojectround',
            name='admission_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionRound'),
        ),
        migrations.AddField(
            model_name='admissionproject',
            name='admission_rounds',
            field=models.ManyToManyField(through='appl.AdmissionProjectRound', to='appl.AdmissionRound'),
        ),
        migrations.AddField(
            model_name='admissionproject',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appl.Campus'),
        ),
    ]
