# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 17:08
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import appl.models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0001_initial'),
        ('appl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUploadedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('descriptions', models.TextField()),
                ('specifications', models.CharField(max_length=100)),
                ('allowed_extentions', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('can_have_multiple_files', models.BooleanField(default=False)),
                ('file_prefix', models.CharField(blank=True, max_length=50)),
                ('size_limit', models.IntegerField(default=2000000)),
                ('admission_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionProject')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('original_filename', models.CharField(max_length=200)),
                ('uploaded_file', models.FileField(upload_to=appl.models.applicant_document_path)),
                ('admission_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionProject')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regis.Applicant')),
                ('project_uploaded_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.ProjectUploadedDocument')),
            ],
        ),
    ]
