# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0004_province_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionround',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
