# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0005_admissionround_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='applying_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เวลาปิดรับสมัคร'),
        ),
        migrations.AddField(
            model_name='admissionproject',
            name='applying_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เวลาเริ่มเปิดรับสมัคร'),
        ),
        migrations.AddField(
            model_name='admissionproject',
            name='is_auto_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionproject',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionproject',
            name='is_started',
            field=models.BooleanField(default=False, verbose_name='เปิดรับสมัครแล้ว'),
        ),
    ]
