# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 02:35
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0002_applicant_passport_number'),
        ('appl', '0006_project_applying_datetime_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_canceled', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('admission_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionProject')),
                ('admission_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionRound')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_applications', to='regis.Applicant')),
            ],
        ),
    ]
