# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0007_projectapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='applying_confirmation_warning',
            field=models.TextField(blank=True, verbose_name='รายละเอียดโครงการ แจ้งยืนยันก่อนสมัคร'),
        ),
    ]
