# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0008_admissionproject_applying_confirmation_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='max_num_selections',
            field=models.IntegerField(default=1, verbose_name='จำนวนสาขาที่เลือกได้'),
        ),
    ]
