# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0009_admissionproject_max_num_selections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='province',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='name',
            new_name='title',
        ),
    ]
