# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0002_applicant_passport_number'),
        ('appl', '0010_auto_20170924_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_selected', models.IntegerField(default=0)),
                ('major_list', models.CharField(blank=True, max_length=50)),
                ('admission_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionProject')),
                ('admission_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionRound')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regis.Applicant')),
                ('project_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appl.ProjectApplication')),
            ],
        ),
    ]
