# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0011_majorselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='base_fee',
            field=models.IntegerField(default=0, verbose_name='ค่าสมัคร'),
        ),
        migrations.AddField(
            model_name='major',
            name='additional_fee_one_time',
            field=models.IntegerField(default=0, verbose_name='ค่าสมัครเพิ่มเติม (ไม่คิดซ้ำ)'),
        ),
        migrations.AddField(
            model_name='major',
            name='additional_fee_per_major',
            field=models.IntegerField(default=0, verbose_name='ค่าสมัครเพิ่มเติม (คิดซ้ำสาขา)'),
        ),
    ]
