# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 14:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0013_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorselection',
            name='project_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='major_selection', to='appl.ProjectApplication'),
        ),
    ]
