# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0014_auto_20170925_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionproject',
            name='applying_deadline',
        ),
        migrations.RemoveField(
            model_name='admissionproject',
            name='applying_start_time',
        ),
        migrations.RemoveField(
            model_name='admissionproject',
            name='is_auto_start',
        ),
        migrations.RemoveField(
            model_name='admissionproject',
            name='is_started',
        ),
        migrations.AddField(
            model_name='admissionprojectround',
            name='applying_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เวลาปิดรับสมัคร'),
        ),
        migrations.AddField(
            model_name='admissionprojectround',
            name='applying_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เวลาเริ่มเปิดรับสมัคร'),
        ),
        migrations.AddField(
            model_name='admissionprojectround',
            name='is_auto_start',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionprojectround',
            name='is_started',
            field=models.BooleanField(default=False, verbose_name='เปิดรับสมัครแล้ว'),
        ),
        migrations.AddField(
            model_name='admissionprojectround',
            name='payment_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='วันชำระค่าสมัครวันสุดท้าย'),
        ),
    ]
