# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0002_applicant_passport_number'),
        ('appl', '0015_move_datetime_fields_to_admissionprojectround'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix_english', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss')], default='Mr.', max_length=4)),
                ('first_name_english', models.CharField(max_length=100, verbose_name='ชื่อ(อังกฤษ)')),
                ('middle_name_english', models.CharField(blank=True, max_length=100, verbose_name='ชื่อกลาง(ถ้ามี)')),
                ('last_name_english', models.CharField(max_length=200, verbose_name='นามสกุล(อังกฤษ)')),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='หมายเลข Passport (ถ้ามี)')),
                ('birthday', models.DateField(verbose_name='วันเดือนปีเกิด')),
                ('father_prefix', models.CharField(max_length=10, verbose_name='คำนำหน้าชื่อบิดา')),
                ('father_first_name', models.CharField(max_length=100, verbose_name='ชื่อบิดา')),
                ('father_last_name', models.CharField(max_length=200, verbose_name='นามสกุลบิดา')),
                ('mother_prefix', models.CharField(max_length=10, verbose_name='คำนำหน้าชื่อมารดา')),
                ('mother_first_name', models.CharField(max_length=100, verbose_name='ชื่อมารดา')),
                ('mother_last_name', models.CharField(max_length=200, verbose_name='นามสกุลมารดา')),
                ('house_number', models.CharField(max_length=10)),
                ('village_number', models.CharField(max_length=10)),
                ('avenue', models.CharField(max_length=100)),
                ('road', models.CharField(max_length=100)),
                ('sub_district', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทรศัพท์ที่ติดต่อได้')),
                ('mobile_phone', models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทรศัพท์มือถือ')),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='regis.Applicant')),
            ],
        ),
    ]
