# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0016_personalprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='avenue',
            field=models.CharField(max_length=100, verbose_name='ซอย'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='district',
            field=models.CharField(max_length=100, verbose_name='อำเภอ/เขต'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='house_number',
            field=models.CharField(max_length=10, verbose_name='บ้านเลขที่'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='รหัสไปรษณีย์'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='province',
            field=models.CharField(max_length=100, verbose_name='จังหวัด'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='road',
            field=models.CharField(max_length=100, verbose_name='ถนน'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='sub_district',
            field=models.CharField(max_length=100, verbose_name='ตำบล/แขวง'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='village_number',
            field=models.CharField(max_length=10, verbose_name='หมู่'),
        ),
    ]
