# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 16:18
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0002_applicant_passport_number'),
        ('appl', '0017_auto_20171002_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.IntegerField(choices=[(1, 'กำลังศึกษาชั้นมัธยมศึกษาปีที่ 6'), (2, 'จบการศึกษาชั้นมัธยมศึกษาปีที่ 6'), (3, 'อื่นๆ')], max_length=3, verbose_name='ระดับการศึกษา')),
                ('education_plan', models.IntegerField(choices=[(1, 'วิทย์-คณิต'), (2, 'อื่นๆ')], max_length=3, verbose_name='แผนการศึกษา')),
                ('gpa', models.FloatField(default=0, verbose_name='GPA')),
                ('school_title', models.CharField(max_length=80, verbose_name='โรงเรียน')),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='regis.Applicant')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.Province', verbose_name='จังหวัด')),
            ],
        ),
    ]
