# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 15:22
from __future__ import unicode_literals

import appl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0017_auto_20171002_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='uploaded_file',
            field=models.ImageField(upload_to=appl.models.applicant_document_path),
        ),
    ]
