# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0018_educationalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprofile',
            name='school_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='educationalprofile',
            name='education_level',
            field=models.IntegerField(choices=[(1, 'กำลังศึกษาชั้นมัธยมศึกษาปีที่ 6'), (2, 'จบการศึกษาชั้นมัธยมศึกษาปีที่ 6'), (3, 'อื่นๆ')], verbose_name='ระดับการศึกษา'),
        ),
        migrations.AlterField(
            model_name='educationalprofile',
            name='education_plan',
            field=models.IntegerField(choices=[(1, 'วิทย์-คณิต'), (2, 'อื่นๆ')], verbose_name='แผนการศึกษา'),
        ),
    ]
