# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0019_auto_20171005_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuploadeddocument',
            name='admission_project',
        ),
        migrations.AddField(
            model_name='projectuploadeddocument',
            name='admission_projects',
            field=models.ManyToManyField(blank=True, to='appl.AdmissionProject'),
        ),
    ]
