# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0020_auto_20171009_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuploadeddocument',
            name='notes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
