# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0023_auto_20171009_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='educationalprofile',
            name='education_level',
            field=models.IntegerField(choices=[(1, 'กำลังศึกษาชั้นมัธยมศึกษาปีที่ 6 หรือเทียบเท่า'), (2, 'จบการศึกษาชั้นมัธยมศึกษาปีที่ 6 หรือเทียบเท่า')], verbose_name='ระดับการศึกษา'),
        ),
        migrations.AlterField(
            model_name='educationalprofile',
            name='education_plan',
            field=models.IntegerField(choices=[(1, 'วิทย์-คณิต'), (2, 'ศิลป์-คำนวณ'), (3, 'ศิลป์-ภาษา'), (4, 'อาชีวศึกษา')], verbose_name='แผนการศึกษา'),
        ),
    ]
