# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0024_auto_20171009_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuploadeddocument',
            name='is_detail_required',
            field=models.BooleanField(default=False),
        ),
    ]
