# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 15:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0025_projectuploadeddocument_is_detail_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='contact_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9]+$', 'เบอร์โทรศัพท์สามารถประกอบด้วยตัวเลข 0-9 และอาจเริ่มต้นด้วยเครื่องหมาย +')], verbose_name='เบอร์โทรศัพท์ที่ติดต่อได้'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='first_name_english',
            field=models.CharField(max_length=100, verbose_name='ชื่อ (อังกฤษ)'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='last_name_english',
            field=models.CharField(max_length=200, verbose_name='นามสกุล (อังกฤษ)'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='middle_name_english',
            field=models.CharField(blank=True, max_length=100, verbose_name='ชื่อกลาง (อังกฤษ, ถ้ามี)'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9]+$', 'เบอร์โทรศัพท์สามารถประกอบด้วยตัวเลข 0-9 และอาจเริ่มต้นด้วยเครื่องหมาย +')], verbose_name='เบอร์โทรศัพท์มือถือ'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='prefix_english',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss')], default='Mr.', max_length=4, verbose_name='คำนำหน้า (อังกฤษ)'),
        ),
    ]
