# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 18:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0026_auto_20171009_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalprofile',
            name='gpa',
            field=models.FloatField(default=0, validators=[django.core.validators.RegexValidator('^[0-3]\\.[0-9]{2}|4\\.00$', 'GPA มีค่าระหว่าง 0.00-4.00 กรุณาตรวจสอบว่าใส่ทศนิยมครบทั้งสองตำแหน่ง')], verbose_name='GPA'),
        ),
    ]
