# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 20:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0027_auto_20171009_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalprofile',
            name='gpa',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)], verbose_name='GPA'),
        ),
    ]
