# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 07:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0028_auto_20171009_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalprofile',
            name='contact_phone',
            field=models.CharField(help_text='หากเป็นเบอร์ติดต่อภายใน ให้ใช้ # คั่น เช่น 034-567-890#111', max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9#-]+$', 'เบอร์โทรศัพท์สามารถประกอบด้วยตัวเลข 0-9 สามารถใช้เครื่องหมาย - เพื่อแบ่งกลุ่มตัวเลข และอาจเริ่มต้นด้วยเครื่องหมาย +')], verbose_name='เบอร์โทรศัพท์ที่ติดต่อได้'),
        ),
        migrations.AlterField(
            model_name='personalprofile',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9#-]+$', 'เบอร์โทรศัพท์สามารถประกอบด้วยตัวเลข 0-9 สามารถใช้เครื่องหมาย - เพื่อแบ่งกลุ่มตัวเลข และอาจเริ่มต้นด้วยเครื่องหมาย +')], verbose_name='เบอร์โทรศัพท์มือถือ'),
        ),
    ]
