# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0029_auto_20171010_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuploadeddocument',
            name='document_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='projectuploadeddocument',
            name='is_url_document',
            field=models.BooleanField(default=False),
        ),
    ]
