# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0030_auto_20171011_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapplication',
            name='verification_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
