# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 04:38
from __future__ import unicode_literals

import appl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0031_projectapplication_verification_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuploadeddocument',
            name='document_url',
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='document_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to=appl.models.applicant_document_path),
        ),
    ]
