# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 15:03
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0004_logitem'),
        ('appl', '0033_admissionprojectround_applicant_info_viewable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_rank', models.IntegerField(default=1)),
                ('is_accepted_for_interview', models.NullBooleanField(default=None)),
                ('updated_accepted_for_interview_at', models.DateTimeField(null=True)),
                ('admission_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionProject')),
                ('admission_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionRound')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regis.Applicant')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.ProjectApplication')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.Major')),
            ],
        ),
        migrations.AddIndex(
            model_name='admissionresult',
            index=models.Index(fields=['application', 'major'], name='appl_admiss_applica_ddc5de_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionresult',
            index=models.Index(fields=['admission_round', 'major'], name='appl_admiss_admissi_d88626_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionresult',
            index=models.Index(fields=['major'], name='appl_admiss_major_i_08d26c_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionresult',
            index=models.Index(fields=['admission_project'], name='appl_admiss_admissi_a25cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionresult',
            index=models.Index(fields=['applicant'], name='appl_admiss_applica_56ddb3_idx'),
        ),
    ]
