# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0036_auto_20171107_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionresult',
            name='clearing_house_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='clearing_house_code_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='is_accepted',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='updated_accepted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='admissionround',
            name='clearing_house_dates',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='admissionround',
            name='clearing_house_description',
            field=models.TextField(blank=True, verbose_name='ข้อมูลการยืนยันสิทธิ์'),
        ),
    ]
