# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0037_auto_20171116_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionprojectround',
            name='accepted_instructions',
            field=models.TextField(blank=True, verbose_name='รายละเอียดแสดงกับผู้สมัครที่ได้รับการคัดเลือกเข้าศึกษา'),
        ),
        migrations.AddField(
            model_name='admissionprojectround',
            name='accepted_result_shown',
            field=models.BooleanField(default=False, verbose_name='แสดงผลการรับเข้าศึกษากับผู้สมัคร'),
        ),
    ]
