# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 14:51
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0038_auto_20171116_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorInterviewDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.TextField()),
                ('admission_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.AdmissionRound')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.Major')),
            ],
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='interview_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='majorinterviewdescription',
            index=models.Index(fields=['admission_round', 'major'], name='appl_majori_admissi_9ebfc2_idx'),
        ),
        migrations.AddIndex(
            model_name='majorinterviewdescription',
            index=models.Index(fields=['major'], name='appl_majori_major_i_9f00de_idx'),
        ),
    ]
