# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-23 11:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0042_major_study_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionresult',
            name='has_confirmed',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='educationalprofile',
            name='education_plan',
            field=models.IntegerField(choices=[(1, 'วิทย์-คณิต'), (2, 'ศิลป์-คำนวณ'), (3, 'ศิลป์-ภาษา'), (4, 'อาชีวศึกษา'), (5, 'ไม่ระบุ')], verbose_name='แผนการศึกษา'),
        ),
        migrations.AlterField(
            model_name='educationalprofile',
            name='gpa',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='GPA'),
        ),
    ]
