# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0043_auto_20171223_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionround',
            name='is_application_available',
            field=models.BooleanField(default=False, verbose_name='ยังแสดงใบสมัครจากรอบนี้ในรอบสมัครอื่น ๆ'),
        ),
        migrations.AlterField(
            model_name='admissionround',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='แสดงเป็นรอบการรับสมัครต่อผู้สมัคร'),
        ),
    ]
