# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 11:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0008_auto_20180131_1151'),
        ('appl', '0044_auto_20180112_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalprofile',
            name='education_plan',
            field=models.IntegerField(choices=[(1, 'วิทย์-คณิต'), (2, 'ศิลป์-คำนวณ'), (3, 'ศิลป์-ภาษา'), (6, 'ศิลป์-สังคม'), (4, 'อาชีวศึกษา'), (5, 'ไม่ระบุ')], verbose_name='แผนการศึกษา'),
        ),
        migrations.AlterField(
            model_name='educationalprofile',
            name='gpa',
            field=models.FloatField(default=0, help_text='ในกรณีที่กำลังศึกษาชั้นม.6 ให้กรอกเกรดเฉลี่ย 5 ภาคการศึกษา ถ้าจบการศึกษาแล้วให้กรอกเกรดเฉลี่ย 6 ภาคการศึกษา', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='GPAX'),
        ),
        migrations.AlterUniqueTogether(
            name='admissionresult',
            unique_together=set([('applicant', 'admission_project', 'major')]),
        ),
    ]
