# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0045_auto_20180131_1151'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projectapplication',
            index=models.Index(fields=['verification_number'], name='appl_projec_verific_370866_idx'),
        ),
    ]
