# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-01 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0046_auto_20180131_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
