# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-25 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0048_admissionprojectround_accepted_result_frozen'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionprojectround',
            name='criteria_check_frozen',
            field=models.BooleanField(default=False, verbose_name='ปิดการแก้ไขผลการตรวจเกณฑ์พื้นฐาน'),
        ),
        migrations.AddField(
            model_name='admissionprojectround',
            name='criteria_check_required',
            field=models.BooleanField(default=False, verbose_name='มีการตรวจเกณฑ์พื้นฐานก่อน'),
        ),
    ]
