# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-25 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0049_auto_20180225_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionresult',
            name='is_criteria_passed',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='updated_criteria_passed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
