# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-05 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0008_auto_20180131_1151'),
        ('appl', '0050_auto_20180225_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=20)),
                ('exam_round', models.CharField(max_length=20)),
                ('exam_list', models.TextField(blank=True)),
                ('score_list', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regis.Applicant')),
            ],
        ),
    ]
