# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-10 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0051_examscore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examscore',
            options={'ordering': ['exam_round']},
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='calculated_score',
            field=models.FloatField(default=0),
        ),
    ]
