# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-10 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0052_auto_20180410_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionprojectround',
            name='applicant_score_viewable',
            field=models.BooleanField(default=False, verbose_name='แสดงคะแนนสำหรับการคัดเลือก'),
        ),
    ]
