# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-11 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0053_admissionprojectround_applicant_score_viewable'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionprojectround',
            name='only_bulk_interview_acceptance',
            field=models.BooleanField(default=False, verbose_name='เรียกสัมภาษณ์ตามคะแนนเท่านั้น'),
        ),
    ]
