# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-23 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0054_admissionprojectround_only_bulk_interview_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='applicant_details_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionproject',
            name='cross_majors_acceptance_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionproject',
            name='has_selections_with_no_ranks',
            field=models.BooleanField(default=False),
        ),
    ]
