# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-04 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0055_auto_20180523_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionresult',
            name='is_tcas_confirmed',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='is_tcas_result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='tcas_acceptance_round_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
