# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-05 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0056_auto_20180604_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionresult',
            name='is_tcas_canceled',
            field=models.NullBooleanField(default=None),
        ),
    ]
