# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-10 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0057_admissionresult_is_tcas_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionresult',
            name='is_interview_absent',
            field=models.NullBooleanField(default=None),
        ),
    ]
