# Generated by Django 2.2.10 on 2020-04-08 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0061_major_cupt_full_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='is_forced_individual_interview_call',
            field=models.BooleanField(default=False, verbose_name='ให้เรียกสัมภาษณ์ไม่ตามคะแนน'),
        ),
        migrations.AlterField(
            model_name='educationalprofile',
            name='gpa',
            field=models.FloatField(default=0, help_text='ในกรณีที่กำลังศึกษาชั้นม.6 ให้กรอกเกรดเฉลี่ย 5 ภาคการศึกษา ถ้าจบการศึกษาแล้วให้กรอกเกรดเฉลี่ย 6 ภาคการศึกษา', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='GPAX'),
        ),
    ]
