# Generated by Django 2.2.10 on 2020-04-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0062_auto_20200408_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorinterviewdescription',
            name='has_document_requirements',
            field=models.BooleanField(default=False, verbose_name='มีเอกสารต้องส่งหรืออัพโหลด'),
        ),
        migrations.AddField(
            model_name='majorinterviewdescription',
            name='has_free_acceptance',
            field=models.BooleanField(default=False, verbose_name='รับโดยไม่ต้องมีกระบวนการอื่น'),
        ),
        migrations.AddField(
            model_name='majorinterviewdescription',
            name='has_online_interview',
            field=models.BooleanField(default=True, verbose_name='มีสอบสัมภาษณ์ออนไลน์'),
        ),
        migrations.AddField(
            model_name='majorinterviewdescription',
            name='has_onsite_interview',
            field=models.BooleanField(default=False, verbose_name='มีสอบสัมภาษณ์ที่สถานที่'),
        ),
        migrations.AddField(
            model_name='majorinterviewdescription',
            name='has_upload_requirements',
            field=models.BooleanField(default=False, verbose_name='มีเอกสารให้อัพโหลดในระบบ'),
        ),
    ]
