# Generated by Django 2.2.17 on 2020-12-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0064_auto_20200409_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalprofile',
            name='lang_credit',
            field=models.IntegerField(default=0, verbose_name='หน่วยกิตกลุ่มสาระภาษาต่างประเทศ'),
        ),
        migrations.AddField(
            model_name='educationalprofile',
            name='math_credit',
            field=models.IntegerField(default=0, verbose_name='หน่วยกิตกลุ่มสาระคณิตศาสตร์'),
        ),
        migrations.AddField(
            model_name='educationalprofile',
            name='sci_credit',
            field=models.IntegerField(default=0, verbose_name='หน่วยกิตกลุ่มสาระวิทยาศาสตร์'),
        ),
    ]
