# Generated by Django 2.2.17 on 2020-12-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0065_auto_20201203_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalprofile',
            name='lang_credit',
            field=models.FloatField(default=0, verbose_name='หน่วยกิตกลุ่มสาระภาษาต่างประเทศ'),
        ),
        migrations.AlterField(
            model_name='educationalprofile',
            name='math_credit',
            field=models.FloatField(default=0, verbose_name='หน่วยกิตกลุ่มสาระคณิตศาสตร์'),
        ),
        migrations.AlterField(
            model_name='educationalprofile',
            name='sci_credit',
            field=models.FloatField(default=0, verbose_name='หน่วยกิตกลุ่มสาระวิทยาศาสตร์'),
        ),
    ]
