# Generated by Django 2.2.17 on 2020-12-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0066_auto_20201205_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='is_visible_in_backoffice',
            field=models.BooleanField(default=False),
        ),
    ]
