# Generated by Django 2.2.17 on 2021-03-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0067_admissionproject_is_visible_in_backoffice'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuploadeddocument',
            name='requirement_key',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
