# Generated by Django 2.2.17 on 2021-03-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0068_projectuploadeddocument_requirement_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuploadeddocument',
            name='requirement_key',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
