# Generated by Django 3.1 on 2021-09-21 03:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0069_auto_20210306_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionresult',
            name='has_confirmed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='admissionresult',
            name='is_accepted',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='admissionresult',
            name='is_accepted_for_interview',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='admissionresult',
            name='is_criteria_passed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='admissionresult',
            name='is_interview_absent',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='admissionresult',
            name='is_tcas_canceled',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='admissionresult',
            name='is_tcas_confirmed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='educationalprofile',
            name='gpa',
            field=models.FloatField(default=0, help_text='สำหรับการคัดเลือก TCAS รอบ 5 <b>ให้กรอกเกรดเฉลี่ย 6 ภาคการศึกษา</b>', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='GPAX'),
        ),
    ]
