# Generated by Django 3.2.7 on 2021-09-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0070_auto_20210921_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='admission_student_type',
            field=models.IntegerField(choices=[(1, 'รับเฉพาะนักเรียนม. 6 ในปีนี้'), (2, 'รับนักเรียนม. 6 และผู้จบการศึกษาแล้ว')], default=1),
        ),
    ]
