# Generated by Django 3.2.7 on 2021-09-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0071_admissionproject_admission_student_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='admission_school_type',
            field=models.IntegerField(choices=[(1, 'ไม่ระบุเงื่อนไข (รับทุกรูปแบบ)'), (2, 'รับเฉพาะ รร.หลักสูตรแกนกลาง'), (3, 'รับเฉพาะ รร.หลักสูตรนานาชาติ'), (4, 'รับเฉพาะ รร.หลักสูตรอาชีวะ'), (5, 'รับเฉพาะ รร.หลักสูตรตามอัธยาศัย (กศน.)')], default=1),
        ),
    ]
