# Generated by Django 2.2.13 on 2021-09-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0072_admissionproject_admission_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='criteria_allow_custom_data',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='admissionproject',
            name='admission_student_type',
            field=models.IntegerField(choices=[(1, 'รับเฉพาะนักเรียนม. 6 ในปีนี้'), (2, 'รับม. 6 และผู้จบการศึกษา')], default=1),
        ),
    ]
