# Generated by Django 2.2.13 on 2021-09-24 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0073_admission_project_with_criteria_custom_data_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissionproject',
            old_name='criteria_allow_custom_data',
            new_name='is_custom_score_criteria_allowed',
        ),
    ]
