# Generated by Django 3.2.7 on 2021-09-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0074_auto_20210924_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionproject',
            name='admission_school_type',
            field=models.IntegerField(choices=[(1, 'ไม่ระบุเงื่อนไข (รับทุกรูปแบบ)'), (2, 'รับเฉพาะ รร.หลักสูตรแกนกลาง'), (3, 'รับเฉพาะ รร.หลักสูตรนานาชาติ'), (4, 'รับเฉพาะ รร.หลักสูตรอาชีวะ'), (5, 'รับเฉพาะ รร.หลักสูตรตามอัธยาศัย (กศน.)'), (6, 'รับเฉพาะ รร.หลักสูตร GED')], default=1),
        ),
    ]
