# Generated by Django 3.2.7 on 2021-10-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0075_alter_admissionproject_admission_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='is_criteria_edit_allowed',
            field=models.BooleanField(default=True, verbose_name='อนุญาตให้ผู้ดูแลโครงการแก้ไขเงื่อนไขการรับ'),
        ),
        migrations.AlterField(
            model_name='admissionproject',
            name='is_custom_score_criteria_allowed',
            field=models.BooleanField(default=True, verbose_name='อนุญาตให้ป้อนเงื่อนไขได้อย่างอิสระ'),
        ),
    ]
