# Generated by Django 4.1.1 on 2022-09-29 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0078_auto_20220828_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='is_cupt_export_only_major_list',
            field=models.BooleanField(default=True, verbose_name='ส่งข้อมูลทปอ.เป็นรายการสาขาเท่านั้น'),
        ),
    ]
