# Generated by Django 4.1.1 on 2023-02-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0079_admissionproject_is_cupt_export_only_major_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalprofile',
            name='sci_credit',
            field=models.FloatField(default=0, verbose_name='หน่วยกิตกลุ่มสาระวิทยาศาสตร์และเทคโนโลยี'),
        ),
    ]
