# Generated by Django 4.1.1 on 2023-09-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0081_majorinterviewdescriptioncache'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='is_custom_graduate_year_allowed',
            field=models.BooleanField(default=False, verbose_name='อนุญาตให้เลือกรูปแบบปีที่จบการศึกษาของผู้สมัคร'),
        ),
    ]
