# Generated by Django 4.1.13 on 2024-02-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0082_admissionproject_is_custom_graduate_year_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='is_auto_select_single_major',
            field=models.BooleanField(default=False, verbose_name='มีสาขาเดียวและเลือกสาขานั้นโดยอัตโนมัติ'),
        ),
    ]
