# Generated by Django 4.1.13 on 2024-08-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0083_admissionproject_is_auto_select_single_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='custom_interview_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันสัมภาษณ์วันสุดท้าย'),
        ),
        migrations.AddField(
            model_name='admissionproject',
            name='custom_interview_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันสัมภาษณ์วันแรก'),
        ),
        migrations.AddField(
            model_name='admissionproject',
            name='is_custom_interview_date_allowed',
            field=models.BooleanField(default=False, verbose_name='อนุญาติให้เลือกวันสัมภาษณ์ได้'),
        ),
    ]
