# Generated by Django 4.1.13 on 2025-03-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0086_admissionround_acceptance_result_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionprojectround',
            name='multimajor_criteria_check_required',
            field=models.BooleanField(default=False, verbose_name='มีการตรวจเกณฑ์พื้นฐานสำหรับการสมัครหลายสาขา'),
        ),
    ]
