# Generated by Django 4.1.13 on 2025-03-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0087_admissionprojectround_multimajor_criteria_check_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionprojectround',
            name='criteria_edit_only_staff_allowed',
            field=models.BooleanField(default=False, verbose_name='อนุญาตให้เจ้าหน้าที่แก้ไขเกณฑ์พื้นฐานเท่านั้น'),
        ),
    ]
