# Generated by Django 4.1.13 on 2025-08-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0088_admissionprojectround_criteria_edit_only_staff_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='is_additional_admission_form_allowed',
            field=models.BooleanField(default=False, verbose_name='อนุญาตให้มีแบบฟอร์มเพิ่มเติม'),
        ),
        migrations.AlterField(
            model_name='admissionprojectround',
            name='criteria_edit_only_staff_allowed',
            field=models.BooleanField(default=False, verbose_name='อนุญาตให้เจ้าหน้าที่แก้ไขผลการตรวจเกณฑ์พื้นฐานเท่านั้น'),
        ),
    ]
