# Generated by Django 4.1.13 on 2025-09-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0089_admissionproject_is_additional_admission_form_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='is_additional_notice_allowed',
            field=models.BooleanField(default=False, verbose_name='อนุญาตให้มีประกาศเพิ่มเติมในระบบรับสมัคร'),
        ),
    ]
