# Generated by Django 4.1.13 on 2025-10-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0090_admissionproject_is_additional_notice_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='is_additional_admission_form_edit_allowed',
            field=models.BooleanField(default=True, verbose_name='อนุญาตให้แก้ไขแบบฟอร์มเพิ่มเติม'),
        ),
    ]
