# Generated by Django 4.1.13 on 2025-10-13 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0091_admissionproject_is_additional_admission_form_edit_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorAdditionalNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('major', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appl.major')),
            ],
        ),
    ]
