# Generated by Django 4.1.13 on 2025-10-13 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0092_majoradditionalnotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorAdditionalAdmissionFormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('size', models.CharField(max_length=20)),
                ('rank', models.IntegerField()),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionaladmissionformfields', to='appl.major')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
