# Generated by Django 4.1.13 on 2025-10-13 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0013_applicant_accepted_application'),
        ('appl', '0093_majoradditionaladmissionformfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantAdditionalAdmissionFormValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('is_auto_extracted', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_admission_form_values', to='regis.applicant')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.majoradditionaladmissionformfield')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appl.major')),
            ],
        ),
        migrations.AddIndex(
            model_name='applicantadditionaladmissionformvalue',
            index=models.Index(fields=['applicant', 'major'], name='appl_applic_applica_ba62f3_idx'),
        ),
    ]
