# Generated by Django 4.1.13 on 2025-10-13 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0094_applicantadditionaladmissionformvalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majoradditionaladmissionformfield',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_admission_form_fields', to='appl.major'),
        ),
    ]
