# Generated by Django 4.1.13 on 2025-10-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0095_alter_majoradditionaladmissionformfield_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='is_apply_link_hidden',
            field=models.BooleanField(default=False, verbose_name='ซ่อนลิงก์สมัคร'),
        ),
    ]
