# Generated by Django 4.1.13 on 2025-10-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0096_admissionproject_is_apply_link_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='is_portfolio_submission_required',
            field=models.BooleanField(default=False, verbose_name='มีการส่งแฟ้มสะสมผลงาน'),
        ),
    ]
