# Generated by Django 4.1.13 on 2025-11-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0097_admissionproject_is_portfolio_submission_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='local_document_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
