# Generated by Django 4.1.13 on 2025-11-14 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0098_uploadeddocument_local_document_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='majoradditionaladmissionformfield',
            name='admission_project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appl.admissionproject'),
        ),
    ]
