# Generated by Django 4.1.13 on 2026-01-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0099_majoradditionaladmissionformfield_admission_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectapplication',
            name='cached_has_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectapplication',
            name='cached_num_majors',
            field=models.IntegerField(default=0),
        ),
    ]
