# Generated by Django 4.1.13 on 2026-02-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0100_projectapplication_cached_has_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuploadeddocument',
            name='requirement_key',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
