# Generated by Django 4.1.13 on 2026-05-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0101_alter_projectuploadeddocument_requirement_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='is_major_with_zero_slots_hidden',
            field=models.BooleanField(default=False, verbose_name='ซ่อนสาขาที่จำนวนรับเป็นศูนย์'),
        ),
    ]
