# Generated by Django 5.2.16 on 2026-07-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0102_admissionproject_is_major_with_zero_slots_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='is_additional_admission_upload_allowed',
            field=models.BooleanField(default=False, verbose_name='อนุญาตให้อัพโหลดเอกสารเพิ่มเติมตามเกณฑ์'),
        ),
    ]
