# Generated by Django 5.2.16 on 2026-08-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0103_admissionproject_is_additional_admission_upload_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='is_additional_admission_late_upload_allowed',
            field=models.BooleanField(default=False, verbose_name='อนุญาตให้เอกสารอัพโหลดเพิ่มเติมอัพโหลดหลังกำหนดได้'),
        ),
        migrations.AddField(
            model_name='admissionproject',
            name='late_upload_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='วันสุดท้ายที่อนุญาตให้อัพโหลดล่าช้าได้'),
        ),
        migrations.AlterField(
            model_name='admissionproject',
            name='is_additional_admission_upload_allowed',
            field=models.BooleanField(default=False, verbose_name='อนุญาตให้อัพโหลดเอกสารเพิ่มเติม'),
        ),
    ]
