# Generated by Django 5.2.16 on 2026-08-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0104_admissionproject_is_additional_admission_late_upload_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='is_cupt_export_zero_score_fields',
            field=models.BooleanField(default=False, verbose_name='ส่งข้อมูลทปอ.โดยไม่ส่งเกณฑ์ขั้นต่ำและคะแนน'),
        ),
    ]
