# Generated by Django 5.2.17 on 2026-09-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0106_projectuploadeddocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuploadeddocument',
            name='validator',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='การตรวจสอบเพิ่มเติม'),
        ),
    ]
