# Generated by Django 5.2.17 on 2026-09-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0107_projectuploadeddocument_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuploadeddocument',
            name='criteria_upload_key',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='projectuploadeddocument',
            name='is_late_upload_allowed',
            field=models.BooleanField(default=False, verbose_name='อัพโหลดหลังหมดเขตได้'),
        ),
        migrations.AddField(
            model_name='projectuploadeddocument',
            name='major_numbers',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='เฉพาะสาขา (หมายเลขสาขา)'),
        ),
    ]
