# Generated by Django 5.2.17 on 2026-09-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0108_projectuploadeddocument_major_numbers_late_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionproject',
            name='title_en',
            field=models.CharField(blank=True, max_length=400, verbose_name='ชื่อภาษาอังกฤษ'),
        ),
        migrations.AddField(
            model_name='campus',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='ชื่อภาษาอังกฤษ'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='ชื่อภาษาอังกฤษ'),
        ),
        migrations.AddField(
            model_name='major',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='ชื่อภาษาอังกฤษ'),
        ),
    ]
