# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
