# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0002_applicant_passport_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together=set([('national_id', 'passport_number')]),
        ),
    ]
