# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 01:00
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0006_cuptconfirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuptRequestQueueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='regis.Applicant')),
            ],
        ),
    ]
