# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0007_cuptrequestqueueitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuptrequestqueueitem',
            options={'ordering': ['created_at']},
        ),
    ]
