# Generated by Django 2.1.3 on 2018-11-19 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0008_auto_20180131_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='confirmed_application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_applicant', to='appl.ProjectApplication'),
        ),
        migrations.AlterField(
            model_name='logitem',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regis.Applicant'),
        ),
    ]
