# Generated by Django 2.2.17 on 2021-02-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0009_auto_20181119_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='additional_data',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
