# Generated by Django 4.1.13 on 2024-04-25 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0011_cuptconfirmation_api_result_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuptUpdatedName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=20)),
                ('updated_value', models.CharField(max_length=200)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regis.applicant')),
            ],
        ),
    ]
