# Generated by Django 4.1.13 on 2024-12-15 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0086_admissionround_acceptance_result_date_and_more'),
        ('regis', '0012_cuptupdatedname'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='accepted_application',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_applicant', to='appl.projectapplication'),
        ),
    ]
